import type { Harness, HarnessNode, HarnessNodeType } from "../types/harness";
import type { ExportBundle, ExportFile } from "./bundleTypes";
import {
  buildExecutionPlan,
  buildHarnessExportJson,
  findNode,
  fileSlug,
  type ExecutionPlan,
} from "./executionPlan";
import { buildNodePromptTemplate, nodeTypeLabels } from "./nodePrompt";

const RUNNER_MODEL = "claude-opus-4-8";
const RUNNER_MAX_TOKENS = 64000;

type RunnerStep = {
  nodeId: string;
  name: string;
  type: HarnessNodeType;
  promptFile: string;
  artifactFile: string;
};

type RunnerUnit =
  | { kind: "node"; step: RunnerStep }
  | {
      kind: "loop";
      name: string;
      maxIterations: number;
      exitConditions: string[];
      steps: RunnerStep[];
    };

type RunnerManifest = {
  harnessName: string;
  runner: { model: string; maxTokens: number };
  units: RunnerUnit[];
};

const buildRunnerStep = (node: HarnessNode, stepNumber: number): RunnerStep => {
  const numbered = String(stepNumber).padStart(2, "0");
  const slug = fileSlug(node.name, node.id);
  return {
    nodeId: node.id,
    name: node.name,
    type: node.type,
    promptFile: `prompts/${numbered}-${slug}.md`,
    artifactFile: `${numbered}-${slug}.md`,
  };
};

const buildManifest = (
  harness: Harness,
  plan: ExecutionPlan,
): { manifest: RunnerManifest; steps: RunnerStep[] } => {
  const steps: RunnerStep[] = [];
  let counter = 0;
  const nextStep = (nodeId: string): RunnerStep | null => {
    const node = findNode(harness, nodeId);
    if (!node) {
      return null;
    }
    counter += 1;
    const step = buildRunnerStep(node, counter);
    steps.push(step);
    return step;
  };

  const units: RunnerUnit[] = [];
  plan.units.forEach((unit) => {
    if (unit.kind === "node") {
      const step = nextStep(unit.nodeId);
      if (step) {
        units.push({ kind: "node", step });
      }
      return;
    }
    const loopSteps = unit.nodeIds
      .map(nextStep)
      .filter((step): step is RunnerStep => step !== null);
    if (loopSteps.length > 0) {
      units.push({
        kind: "loop",
        name: unit.name,
        maxIterations: Math.max(1, unit.maxIterations),
        exitConditions: unit.exitConditions,
        steps: loopSteps,
      });
    }
  });

  return {
    manifest: {
      harnessName: harness.name,
      runner: { model: RUNNER_MODEL, maxTokens: RUNNER_MAX_TOKENS },
      units,
    },
    steps,
  };
};

const systemPromptFile = (harness: Harness): ExportFile => {
  const pack = harness.contextPack;
  const section = (title: string, items: string[]) =>
    items.length > 0 ? `\n## ${title}\n\n${items.map((item) => `- ${item}`).join("\n")}\n` : "";

  return {
    path: "system.md",
    content: `# Harness: ${harness.name}

${harness.description || ""}

You are executing one step of a multi-step agent harness. Your entire response
is saved as an artifact file and consumed by later workflow steps, so respond
with the deliverable content itself — no conversational preamble, no closing
questions. Follow the step instructions in the user message exactly.
${section("Project Facts", pack.projectFacts)}${section("Domain Notes", pack.domainNotes)}${section(
      "Source Map",
      pack.sourceMap,
    )}${section("Conventions", pack.conventions)}${section(
      "Reusable Constraints",
      pack.reusableConstraints,
    )}${section("Validation Commands", pack.validationCommands)}${section(
      "Known Risks",
      pack.knownRisks,
    )}`,
  };
};

const promptFile = (harness: Harness, node: HarnessNode, step: RunnerStep): ExportFile => {
  let content = buildNodePromptTemplate(harness, node);
  if (node.type === "gate") {
    content += `\n## Response Format

Your response is parsed as JSON with the fields \`pass\` (boolean), \`reasons\`
(string array), and \`fixInstructions\` (string; concrete instructions for the
next iteration when failing, otherwise an empty string). Base the verdict only
on the quality gates, exit conditions, and the provided artifacts.
`;
  }
  return { path: step.promptFile, content };
};

// The generated engine deliberately avoids template literals so this template
// needs no backtick/interpolation escaping.
const RUN_MJS = `#!/usr/bin/env node
// Harness runner generated by Harness Studio.
//
// Executes the workflow described in manifest.json against the Anthropic API.
// Step prompts live in prompts/ and may be edited freely; manifest.json
// controls ordering, loops, and the model configuration.
//
// Usage:
//   export ANTHROPIC_API_KEY=sk-ant-...
//   node run.mjs "<task description>"

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import Anthropic from "@anthropic-ai/sdk";

const here = path.dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(fs.readFileSync(path.join(here, "manifest.json"), "utf8"));
const systemPrompt = fs.readFileSync(path.join(here, "system.md"), "utf8");

const task = process.argv.slice(2).join(" ").trim();
if (!task) {
  console.error('Usage: node run.mjs "<task description>"');
  process.exit(1);
}
if (!process.env.ANTHROPIC_API_KEY && !process.env.ANTHROPIC_AUTH_TOKEN) {
  console.error("Set ANTHROPIC_API_KEY (or ANTHROPIC_AUTH_TOKEN) before running.");
  process.exit(1);
}

const client = new Anthropic();
const stamp = new Date().toISOString().replace(/[:.]/g, "-");
const runDir = path.join(here, "runs", stamp);
fs.mkdirSync(runDir, { recursive: true });

const MAX_ARTIFACT_CHARS = 60000;
const artifacts = []; // { nodeId, name, content } — latest output per step
const summary = [];

const VERDICT_SCHEMA = {
  type: "object",
  properties: {
    pass: { type: "boolean" },
    reasons: { type: "array", items: { type: "string" } },
    fixInstructions: { type: "string" },
  },
  required: ["pass", "reasons", "fixInstructions"],
  additionalProperties: false,
};

function upstreamSection() {
  if (artifacts.length === 0) {
    return "This is the first step. There are no upstream artifacts; work from the task itself.";
  }
  return artifacts
    .map(function (artifact) {
      const body =
        artifact.content.length > MAX_ARTIFACT_CHARS
          ? artifact.content.slice(0, MAX_ARTIFACT_CHARS) + "\\n...[truncated]"
          : artifact.content;
      return '### Output of step "' + artifact.name + '"\\n\\n' + body;
    })
    .join("\\n\\n");
}

async function callClaude(userText, options) {
  const structured = Boolean(options && options.structured);
  const request = {
    model: manifest.runner.model,
    max_tokens: manifest.runner.maxTokens,
    thinking: { type: "adaptive" },
    system: [
      { type: "text", text: systemPrompt, cache_control: { type: "ephemeral" } },
    ],
    messages: [{ role: "user", content: userText }],
  };
  if (structured) {
    request.output_config = { format: { type: "json_schema", schema: VERDICT_SCHEMA } };
  }
  const stream = client.messages.stream(request);
  if (!structured) {
    stream.on("text", function (delta) {
      process.stdout.write(delta);
    });
  }
  const message = await stream.finalMessage();
  if (!structured) {
    process.stdout.write("\\n");
  }
  return message.content
    .filter(function (block) {
      return block.type === "text";
    })
    .map(function (block) {
      return block.text;
    })
    .join("\\n");
}

function parseVerdict(raw) {
  try {
    return JSON.parse(raw);
  } catch {
    return {
      pass: false,
      reasons: ["The gate response could not be parsed as JSON."],
      fixInstructions: raw.slice(0, 2000),
    };
  }
}

function loadPrompt(step, loopFeedback) {
  const template = fs.readFileSync(path.join(here, step.promptFile), "utf8");
  let taskText = task;
  if (loopFeedback) {
    taskText +=
      "\\n\\n### Feedback from the previous loop iteration (address this first)\\n\\n" +
      loopFeedback;
  }
  // Function replacements keep "$&"-style sequences in the task text literal.
  return template
    .replace("{{TASK}}", function () {
      return taskText;
    })
    .replace("{{UPSTREAM}}", function () {
      return upstreamSection();
    });
}

function saveArtifact(step, content, iteration) {
  const suffix = iteration ? ".iter" + iteration : "";
  const fileName = step.artifactFile.replace(/\\.md$/, suffix + ".md");
  fs.writeFileSync(path.join(runDir, fileName), content);
  const entry = { nodeId: step.nodeId, name: step.name, content: content };
  const existing = artifacts.findIndex(function (artifact) {
    return artifact.nodeId === step.nodeId;
  });
  if (existing >= 0) {
    artifacts[existing] = entry;
  } else {
    artifacts.push(entry);
  }
}

async function runStep(step, options) {
  const iteration = options && options.iteration;
  const loopFeedback = options && options.loopFeedback;
  const header =
    "=== Step: " +
    step.name +
    " (" +
    step.type +
    ")" +
    (iteration ? " [iteration " + iteration + "]" : "") +
    " ===";
  console.log("\\n" + header + "\\n");

  const prompt = loadPrompt(step, loopFeedback);

  if (step.type === "gate") {
    const raw = await callClaude(prompt, { structured: true });
    const verdict = parseVerdict(raw);
    const report = [
      "# Gate: " + step.name,
      "",
      "Verdict: " + (verdict.pass ? "PASS" : "FAIL"),
      "",
      "Reasons:",
      verdict.reasons
        .map(function (reason) {
          return "- " + reason;
        })
        .join("\\n"),
      verdict.fixInstructions ? "\\nFix instructions:\\n" + verdict.fixInstructions : "",
    ].join("\\n");
    saveArtifact(step, report, iteration);
    console.log("Gate verdict: " + (verdict.pass ? "PASS" : "FAIL"));
    verdict.reasons.forEach(function (reason) {
      console.log("- " + reason);
    });
    return { verdict: verdict };
  }

  const output = await callClaude(prompt);
  saveArtifact(step, output, iteration);
  return { output: output };
}

async function judgeLoopExit(unit) {
  const prompt = [
    'You are the exit-condition judge for the workflow loop "' + unit.name + '".',
    "Decide whether ALL of the following exit conditions are satisfied by the artifacts below.",
    "",
    "Exit conditions:",
    unit.exitConditions
      .map(function (condition) {
        return "- " + condition;
      })
      .join("\\n"),
    "",
    "Task:",
    task,
    "",
    "Artifacts:",
    upstreamSection(),
  ].join("\\n");
  const raw = await callClaude(prompt, { structured: true });
  return parseVerdict(raw);
}

async function runLoop(unit) {
  let feedback = "";
  for (let iteration = 1; iteration <= unit.maxIterations; iteration += 1) {
    let gateVerdict = null;
    for (const step of unit.steps) {
      const result = await runStep(step, {
        iteration: iteration,
        loopFeedback: feedback || undefined,
      });
      if (result.verdict) {
        gateVerdict = result.verdict;
      }
    }
    const verdict =
      gateVerdict !== null
        ? gateVerdict
        : unit.exitConditions.length > 0
          ? await judgeLoopExit(unit)
          : { pass: true, reasons: ["Loop has no gate step and no exit conditions."], fixInstructions: "" };
    if (verdict.pass) {
      summary.push('Loop "' + unit.name + '" satisfied after ' + iteration + " iteration(s).");
      return;
    }
    feedback = verdict.reasons
      .concat(verdict.fixInstructions ? [verdict.fixInstructions] : [])
      .join("\\n");
    summary.push('Loop "' + unit.name + '" iteration ' + iteration + ": FAIL");
  }
  summary.push(
    'Loop "' +
      unit.name +
      '" UNRESOLVED after ' +
      unit.maxIterations +
      " iterations — continuing with remaining steps. Review the latest iteration artifacts.",
  );
}

let stopped = false;
try {
  for (const unit of manifest.units) {
    if (stopped) {
      break;
    }
    if (unit.kind === "node") {
      const result = await runStep(unit.step);
      summary.push('Step "' + unit.step.name + '" completed.');
      if (unit.step.type === "gate" && result.verdict && !result.verdict.pass) {
        summary.push('Gate "' + unit.step.name + '" FAILED outside a loop — run stopped.');
        console.error("\\nGate failed outside a loop. Stopping the run.");
        stopped = true;
      }
    } else {
      await runLoop(unit);
    }
  }
} catch (error) {
  if (error instanceof Anthropic.APIError) {
    summary.push("Run aborted by Anthropic API error " + error.status + ": " + error.message);
    console.error("\\nAnthropic API error " + error.status + ": " + error.message);
  } else {
    summary.push("Run aborted by unexpected error: " + String(error));
    console.error(error);
  }
  process.exitCode = 1;
}

const summaryText = [
  "# Run Summary: " + manifest.harnessName,
  "",
  "Task:",
  "",
  task,
  "",
  "Result log:",
  "",
  summary
    .map(function (line) {
      return "- " + line;
    })
    .join("\\n"),
  "",
  "Artifacts directory: " + runDir,
].join("\\n");
fs.writeFileSync(path.join(runDir, "run-summary.md"), summaryText);
console.log("\\n" + summaryText);
`;

const runnerReadme = (harness: Harness, steps: RunnerStep[]): ExportFile => ({
  path: "README.md",
  content: `# ${harness.name} — Agent Runner Pack

Harness Studio で設計したワークフローを、Anthropic API 上でプログラムとして実行する
スタンドアロンのランナーです。各ステップをモデル(${RUNNER_MODEL})への呼び出しとして
順番に実行し、ループは Quality Gate / 終了条件の判定結果に従って反復します。

> コードベースを直接編集するワークフローには、ツール(ファイル操作・コマンド実行)を
> 持つ Claude Code Pack のエクスポートを推奨します。このランナーは調査・設計・
> 文書生成・レビューといった「テキスト成果物のパイプライン」、およびアプリへの
> 組み込みの土台に向いています。

## セットアップ

1. Node.js 20 以上を用意します。
2. 依存関係をインストールします。

   \`\`\`bash
   npm install
   \`\`\`

3. API キーを設定します(.env.example 参照)。

   \`\`\`bash
   export ANTHROPIC_API_KEY=sk-ant-...
   \`\`\`

## 実行

\`\`\`bash
node run.mjs "ここに実行したいタスクを書く"
\`\`\`

- 各ステップの出力は \`runs/<タイムスタンプ>/\` に成果物ファイルとして保存されます。
- Quality Gate ステップは構造化出力(JSON)で PASS / FAIL を判定します。
- ループは Gate の FAIL 理由と修正指示を次の反復に引き継ぎ、最大反復回数に達した
  場合は UNRESOLVED として記録した上で残りのステップを続行します。
- 実行終了時に \`run-summary.md\` が生成されます。

## ファイル構成

| パス | 内容 |
| --- | --- |
| \`run.mjs\` | ワークフロー実行エンジン(編集可) |
| \`manifest.json\` | 実行計画(ステップ順・ループ・モデル設定) |
| \`system.md\` | 全ステップ共通のシステムプロンプト(Context Pack 由来) |
| \`prompts/\` | 各ステップのプロンプト(自由に編集可) |
| \`harness.json\` | ハーネス設計の機械可読データ(原本) |

## ステップ一覧

${steps.map((step, index) => `${index + 1}. ${step.name} (${nodeTypeLabels[step.type]}) — \`${step.promptFile}\``).join("\n")}

Generated by Harness Studio.
`,
});

const runnerPackageJson = (harness: Harness): ExportFile => ({
  path: "package.json",
  content: `${JSON.stringify(
    {
      name: `${fileSlug(harness.name, harness.id)}-harness-runner`,
      private: true,
      version: "0.1.0",
      type: "module",
      scripts: {
        start: "node run.mjs",
      },
      dependencies: {
        "@anthropic-ai/sdk": "latest",
      },
    },
    null,
    2,
  )}\n`,
});

export function buildAgentRunnerPack(harness: Harness): ExportBundle {
  const plan = buildExecutionPlan(harness);
  const { manifest, steps } = buildManifest(harness, plan);

  const promptFiles = steps
    .map((step) => {
      const node = findNode(harness, step.nodeId);
      return node ? promptFile(harness, node, step) : null;
    })
    .filter((file): file is ExportFile => file !== null);

  const files: ExportFile[] = [
    runnerReadme(harness, steps),
    runnerPackageJson(harness),
    { path: ".env.example", content: "ANTHROPIC_API_KEY=sk-ant-...\n" },
    { path: "run.mjs", content: RUN_MJS },
    { path: "manifest.json", content: `${JSON.stringify(manifest, null, 2)}\n` },
    systemPromptFile(harness),
    ...promptFiles,
    {
      path: "harness.json",
      content: `${JSON.stringify(buildHarnessExportJson(harness), null, 2)}\n`,
    },
  ];

  return {
    name: `${fileSlug(harness.name, harness.id)}-agent-runner`,
    description:
      "Anthropic API でワークフローを自動実行するランナー(npm install && node run.mjs で実行可能)",
    files,
  };
}
