import type { StepKind, Workflow } from "../types/workflow";
import { stepKindPresets } from "../data/stepKinds";
import type { ExportBundle, ExportFile } from "./bundleTypes";
import { fileSlug, planWorkflow, type PlannedStep, type WorkflowPlan } from "./plan";
import { buildStepPromptTemplate, gateVerdictJsonInstruction } from "./stepPrompt";
import { buildWorkflowJson } from "./workflowJson";

const DEFAULT_SANDBOX_MODE = "workspace-write";

type ManifestStep = {
  stepId: string;
  name: string;
  kind: StepKind;
  promptFile: string;
  artifactFile: string;
};

type ManifestUnit =
  | { kind: "step"; step: ManifestStep }
  | {
      kind: "loop";
      name: string;
      maxIterations: number;
      exitCondition: string;
      steps: ManifestStep[];
    };

const manifestStep = (planned: PlannedStep): ManifestStep => ({
  stepId: planned.step.id,
  name: planned.step.name,
  kind: planned.step.kind,
  promptFile: `prompts/${planned.slug}.md`,
  artifactFile: `${planned.slug}.md`,
});

const buildManifest = (workflow: Workflow, plan: WorkflowPlan) => ({
  workflowName: workflow.name,
  runner: {
    // Codex thread settings. model: null uses the Codex CLI default model.
    sandboxMode: DEFAULT_SANDBOX_MODE,
    model: null as string | null,
  },
  units: plan.units.map((unit): ManifestUnit => {
    if (unit.kind === "step") {
      return { kind: "step", step: manifestStep(unit.planned) };
    }
    return {
      kind: "loop",
      name: unit.block.name,
      maxIterations: Math.max(1, unit.block.maxIterations),
      exitCondition: unit.block.exitCondition,
      steps: unit.planned.map(manifestStep),
    };
  }),
});

const promptFile = (workflow: Workflow, planned: PlannedStep): ExportFile => {
  let content = buildStepPromptTemplate(workflow, planned.step);
  if (planned.step.kind === "gate") {
    content += `\n${gateVerdictJsonInstruction()}`;
  }
  return { path: `prompts/${planned.slug}.md`, content };
};

const agentsMd = (workflow: Workflow): ExportFile => ({
  path: "AGENTS.md",
  content: `# ${workflow.name}

${workflow.description || ""}

${workflow.context ? `## Shared Context\n\n${workflow.context}\n` : ""}
## How This Repository Is Worked On

This guidance accompanies the "${workflow.name}" workflow generated by Harness
Studio. Copy this file into the target repository root — the Codex agent reads
AGENTS.md from its working directory automatically.
`,
});

// The generated engine deliberately avoids template literals so this template
// needs no backtick/interpolation escaping.
const RUN_MJS = `#!/usr/bin/env node
// Workflow runner generated by Harness Studio — powered by the OpenAI Codex SDK.
//
// Each workflow step runs as a Codex agent thread that can read files, edit
// files, and run commands inside the target directory (within the configured
// sandbox mode). Step outputs are saved as artifacts and handed to later steps.
//
// Usage:
//   npm install
//   codex login                # or: export CODEX_API_KEY=...
//   node run.mjs [--dir <target-directory>] "<task description>"
//
// --dir defaults to the current working directory.

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { Codex } from "@openai/codex-sdk";

const here = path.dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(fs.readFileSync(path.join(here, "manifest.json"), "utf8"));

const args = process.argv.slice(2);
let workingDirectory = process.cwd();
const taskParts = [];
for (let i = 0; i < args.length; i += 1) {
  if (args[i] === "--dir" && args[i + 1]) {
    workingDirectory = path.resolve(args[i + 1]);
    i += 1;
  } else {
    taskParts.push(args[i]);
  }
}
const task = taskParts.join(" ").trim();
if (!task) {
  console.error('Usage: node run.mjs [--dir <target-directory>] "<task description>"');
  process.exit(1);
}
if (!fs.existsSync(workingDirectory)) {
  console.error("Target directory does not exist: " + workingDirectory);
  process.exit(1);
}

const codex = new Codex();
const stamp = new Date().toISOString().replace(/[:.]/g, "-");
const runDir = path.join(here, "runs", stamp);
fs.mkdirSync(runDir, { recursive: true });

const MAX_ARTIFACT_CHARS = 60000;
const artifacts = []; // { stepId, name, content } — latest output per step
const summary = [];

const VERDICT_SCHEMA = {
  type: "object",
  properties: {
    pass: { type: "boolean" },
    reasons: { type: "array", items: { type: "string" } },
    fixInstructions: { type: "string" },
  },
  required: ["pass", "reasons", "fixInstructions"],
  additionalProperties: false,
};

function newThread() {
  const options = {
    workingDirectory: workingDirectory,
    sandboxMode: manifest.runner.sandboxMode,
    skipGitRepoCheck: true,
  };
  if (manifest.runner.model) {
    options.model = manifest.runner.model;
  }
  return codex.startThread(options);
}

function upstreamSection() {
  if (artifacts.length === 0) {
    return "This is the first step. There are no upstream outputs; work from the task and the files in your working directory.";
  }
  return artifacts
    .map(function (artifact) {
      const body =
        artifact.content.length > MAX_ARTIFACT_CHARS
          ? artifact.content.slice(0, MAX_ARTIFACT_CHARS) + "\\n...[truncated]"
          : artifact.content;
      return '### Output of step "' + artifact.name + '"\\n\\n' + body;
    })
    .join("\\n\\n");
}

function loadPrompt(step, loopFeedback) {
  const template = fs.readFileSync(path.join(here, step.promptFile), "utf8");
  let taskText = task;
  if (loopFeedback) {
    taskText +=
      "\\n\\n### Feedback from the previous attempt (address this first)\\n\\n" + loopFeedback;
  }
  // Function replacements keep "$&"-style sequences in the task text literal.
  return template
    .replace("{{TASK}}", function () {
      return taskText;
    })
    .replace("{{UPSTREAM}}", function () {
      return upstreamSection();
    });
}

function saveArtifact(step, content, iteration) {
  const suffix = iteration ? ".iter" + iteration : "";
  const fileName = step.artifactFile.replace(/\\.md$/, suffix + ".md");
  fs.writeFileSync(path.join(runDir, fileName), content);
  const entry = { stepId: step.stepId, name: step.name, content: content };
  const existing = artifacts.findIndex(function (artifact) {
    return artifact.stepId === step.stepId;
  });
  if (existing >= 0) {
    artifacts[existing] = entry;
  } else {
    artifacts.push(entry);
  }
}

function parseVerdict(raw) {
  try {
    return JSON.parse(raw);
  } catch {
    return {
      pass: false,
      reasons: ["The gate response could not be parsed as JSON."],
      fixInstructions: String(raw).slice(0, 2000),
    };
  }
}

// Runs one Codex turn, printing progress (commands, file changes, messages).
async function runCodex(prompt, options) {
  const structured = Boolean(options && options.structured);
  const thread = newThread();

  if (structured) {
    const turn = await thread.run(prompt, { outputSchema: VERDICT_SCHEMA });
    return turn.finalResponse;
  }

  const streamed = await thread.runStreamed(prompt);
  let finalResponse = "";
  for await (const event of streamed.events) {
    if (event.type === "item.completed") {
      const item = event.item;
      if (item.type === "agent_message") {
        finalResponse = item.text;
        console.log(item.text);
      } else if (item.type === "command_execution") {
        const exit = typeof item.exit_code === "number" ? " (exit " + item.exit_code + ")" : "";
        console.log("  $ " + item.command + exit);
      } else if (item.type === "file_change") {
        item.changes.forEach(function (change) {
          console.log("  ~ " + change.kind + " " + change.path);
        });
      } else if (item.type === "web_search") {
        console.log("  ? search: " + item.query);
      } else if (item.type === "error") {
        console.error("  ! " + item.message);
      }
    } else if (event.type === "turn.failed") {
      throw new Error(event.error && event.error.message ? event.error.message : "Turn failed.");
    } else if (event.type === "error") {
      throw new Error(event.message);
    }
  }
  return finalResponse;
}

async function runStep(step, options) {
  const iteration = options && options.iteration;
  const loopFeedback = options && options.loopFeedback;
  const header =
    "=== Step: " +
    step.name +
    " (" +
    step.kind +
    ")" +
    (iteration ? " [attempt " + iteration + "]" : "") +
    " ===";
  console.log("\\n" + header + "\\n");

  const prompt = loadPrompt(step, loopFeedback);

  if (step.kind === "gate") {
    const raw = await runCodex(prompt, { structured: true });
    const verdict = parseVerdict(raw);
    const report = [
      "# Gate: " + step.name,
      "",
      "Verdict: " + (verdict.pass ? "PASS" : "FAIL"),
      "",
      "Reasons:",
      (verdict.reasons || [])
        .map(function (reason) {
          return "- " + reason;
        })
        .join("\\n"),
      verdict.fixInstructions ? "\\nFix instructions:\\n" + verdict.fixInstructions : "",
    ].join("\\n");
    saveArtifact(step, report, iteration);
    console.log("Gate verdict: " + (verdict.pass ? "PASS" : "FAIL"));
    (verdict.reasons || []).forEach(function (reason) {
      console.log("- " + reason);
    });
    return { verdict: verdict };
  }

  const output = await runCodex(prompt);
  saveArtifact(step, output, iteration);
  return { output: output };
}

async function judgeLoopExit(unit) {
  const prompt = [
    'You are the exit-condition judge for the workflow loop "' + unit.name + '".',
    "Inspect the working directory and the outputs below, then decide whether the",
    "following exit condition is satisfied:",
    "",
    "Exit condition: " + unit.exitCondition,
    "",
    "Task:",
    task,
    "",
    "Outputs so far:",
    upstreamSection(),
  ].join("\\n");
  const raw = await runCodex(prompt, { structured: true });
  return parseVerdict(raw);
}

async function runLoop(unit) {
  let feedback = "";
  for (let iteration = 1; iteration <= unit.maxIterations; iteration += 1) {
    let gateVerdict = null;
    for (const step of unit.steps) {
      const result = await runStep(step, {
        iteration: iteration,
        loopFeedback: feedback || undefined,
      });
      if (result.verdict) {
        gateVerdict = result.verdict;
      }
    }
    const verdict =
      gateVerdict !== null
        ? gateVerdict
        : unit.exitCondition
          ? await judgeLoopExit(unit)
          : { pass: true, reasons: ["Loop has no gate step and no exit condition."], fixInstructions: "" };
    if (verdict.pass) {
      summary.push('Loop "' + unit.name + '" satisfied after ' + iteration + " attempt(s).");
      return;
    }
    feedback = (verdict.reasons || [])
      .concat(verdict.fixInstructions ? [verdict.fixInstructions] : [])
      .join("\\n");
    summary.push('Loop "' + unit.name + '" attempt ' + iteration + ": FAIL");
  }
  summary.push(
    'Loop "' +
      unit.name +
      '" UNRESOLVED after ' +
      unit.maxIterations +
      " attempts — continuing with remaining steps. Review the latest attempt artifacts.",
  );
}

console.log("Workflow: " + manifest.workflowName);
console.log("Target directory: " + workingDirectory);
console.log("Sandbox mode: " + manifest.runner.sandboxMode);

let stopped = false;
try {
  for (const unit of manifest.units) {
    if (stopped) {
      break;
    }
    if (unit.kind === "step") {
      const result = await runStep(unit.step);
      summary.push('Step "' + unit.step.name + '" completed.');
      if (unit.step.kind === "gate" && result.verdict && !result.verdict.pass) {
        summary.push('Gate "' + unit.step.name + '" FAILED outside a loop — run stopped.');
        console.error("\\nGate failed outside a loop. Stopping the run.");
        stopped = true;
      }
    } else {
      await runLoop(unit);
    }
  }
} catch (error) {
  summary.push("Run aborted: " + (error && error.message ? error.message : String(error)));
  console.error(error);
  process.exitCode = 1;
}

const summaryText = [
  "# Run Summary: " + manifest.workflowName,
  "",
  "Task:",
  "",
  task,
  "",
  "Target directory: " + workingDirectory,
  "",
  "Result log:",
  "",
  summary
    .map(function (line) {
      return "- " + line;
    })
    .join("\\n"),
  "",
  "Artifacts directory: " + runDir,
].join("\\n");
fs.writeFileSync(path.join(runDir, "run-summary.md"), summaryText);
console.log("\\n" + summaryText);
`;

// Self-improvement assistant: reviews a past run and improves the step
// prompts. Also avoids template literals to skip escaping.
const IMPROVE_MJS = `#!/usr/bin/env node
// Self-improvement loop generated by Harness Studio.
//
// Reviews the artifacts of a previous run and improves this pack's step
// prompts based on what actually happened. The Codex agent only sees this
// pack directory; with --apply it may edit files under prompts/ directly.
//
// Usage:
//   node improve.mjs                      # analyze the latest run, report only
//   node improve.mjs --apply              # let Codex edit prompts/*.md directly
//   node improve.mjs --run runs/<stamp>   # analyze a specific run
//
// Recommended cycle:
//   node run.mjs --dir <repo> "<task>"   ->   node improve.mjs --apply
//   -> review the prompt diff (git diff) ->   run again
//
// Keep this pack under git so every applied improvement is reviewable and
// reversible. The loop is intentionally human-paced: one improvement pass per
// invocation, no unbounded self-modification.

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { Codex } from "@openai/codex-sdk";

const here = path.dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const apply = args.includes("--apply");
let runDirArg = null;
const runFlagIndex = args.indexOf("--run");
if (runFlagIndex >= 0 && args[runFlagIndex + 1]) {
  runDirArg = args[runFlagIndex + 1];
}

const runsRoot = path.join(here, "runs");
let runDir = runDirArg ? path.resolve(here, runDirArg) : null;
if (!runDir) {
  const candidates = fs.existsSync(runsRoot)
    ? fs.readdirSync(runsRoot).filter(function (name) {
        return fs.statSync(path.join(runsRoot, name)).isDirectory();
      })
    : [];
  if (candidates.length === 0) {
    console.error('No runs found. Execute the workflow first: node run.mjs "<task>"');
    process.exit(1);
  }
  candidates.sort();
  runDir = path.join(runsRoot, candidates[candidates.length - 1]);
}
if (!fs.existsSync(runDir)) {
  console.error("Run directory does not exist: " + runDir);
  process.exit(1);
}

const relRunDir = path.relative(here, runDir);
console.log("Analyzing run: " + relRunDir + (apply ? " (apply mode)" : " (report only)"));

const editRules = [
  "Edit the prompt files under prompts/ directly with concrete improvements.",
  "Hard rules:",
  "- Only modify files inside prompts/.",
  "- Keep the {{TASK}} and {{UPSTREAM}} placeholders — exactly one occurrence of each per file.",
  "- Do not change manifest.json, run.mjs, workflow.json, AGENTS.md, or this script.",
  "- Keep each prompt's section structure; sharpen instructions, success criteria, and verdict criteria instead of rewriting wholesale.",
].join("\\n");

const reportRules = [
  "Do NOT edit any file. For each prompt file that should change, output:",
  "- the file path,",
  "- what went wrong in the run that motivates the change,",
  "- the exact replacement text for the section(s) to update.",
].join("\\n");

const prompt = [
  "You are the self-improvement reviewer for an agentic workflow pack.",
  "This directory contains: manifest.json (the execution plan), prompts/ (one prompt per step),",
  "and " + relRunDir + "/ (artifacts of a finished run: per-step outputs, gate verdicts, run-summary.md).",
  "",
  "1. Read " + relRunDir + "/run-summary.md, then the step artifacts in that directory, then the prompts in prompts/.",
  "2. Diagnose where the workflow underperformed: vague instructions, missing constraints,",
  "   gates that passed or failed for the wrong reasons, loops that hit their attempt limit,",
  "   steps whose outputs were not useful to later steps.",
  "3. " + (apply ? editRules : reportRules),
  "",
  "Finish with a summary: each change (or proposal), the evidence from the run that motivates it,",
  "and what should improve on the next run.",
].join("\\n");

const codex = new Codex();
const thread = codex.startThread({
  workingDirectory: here,
  sandboxMode: apply ? "workspace-write" : "read-only",
  skipGitRepoCheck: true,
});

const streamed = await thread.runStreamed(prompt);
let finalResponse = "";
for await (const event of streamed.events) {
  if (event.type === "item.completed") {
    const item = event.item;
    if (item.type === "agent_message") {
      finalResponse = item.text;
      console.log(item.text);
    } else if (item.type === "command_execution") {
      const exit = typeof item.exit_code === "number" ? " (exit " + item.exit_code + ")" : "";
      console.log("  $ " + item.command + exit);
    } else if (item.type === "file_change") {
      item.changes.forEach(function (change) {
        console.log("  ~ " + change.kind + " " + change.path);
      });
    } else if (item.type === "error") {
      console.error("  ! " + item.message);
    }
  } else if (event.type === "turn.failed") {
    throw new Error(event.error && event.error.message ? event.error.message : "Turn failed.");
  } else if (event.type === "error") {
    throw new Error(event.message);
  }
}

fs.writeFileSync(path.join(runDir, "improvement-report.md"), finalResponse);
console.log("\\nImprovement report saved to " + path.join(relRunDir, "improvement-report.md"));
if (apply) {
  console.log("Prompts may have been edited. Review the diff (git diff prompts/) before the next run.");
}
`;

const runnerReadme = (workflow: Workflow, steps: PlannedStep[]): ExportFile => ({
  path: "README.md",
  content: `# ${workflow.name} — Codex Workflow Runner

Harness Studio で作成したワークフローを、**OpenAI Codex SDK** で実際に実行する
ランナーです。各ステップは Codex のエージェントスレッドとして実行され、対象
ディレクトリの中でファイルの読み書き・コマンド実行ができます(サンドボックス内)。

## セットアップ

1. Node.js 18 以上を用意します。
2. 依存関係をインストールします。

   \`\`\`bash
   npm install
   \`\`\`

3. Codex の認証を済ませます(どちらか)。

   \`\`\`bash
   codex login                # ChatGPT アカウントでログイン
   export CODEX_API_KEY=...   # または API キー
   \`\`\`

## 実行

\`\`\`bash
# 対象リポジトリのディレクトリを指定して実行
node run.mjs --dir /path/to/your-repo "ここに実行したいタスクを書く"

# --dir を省略すると、いま居るディレクトリが対象になります
node run.mjs "ここに実行したいタスクを書く"
\`\`\`

- 各ステップの出力は \`runs/<タイムスタンプ>/\` に保存され、後続ステップに引き継がれます。
- 「チェック」ステップは構造化出力(JSON)で PASS / FAIL を判定します。
- ループは不合格の理由と修正指示を次の試行に引き継ぎ、最大回数に達したら
  UNRESOLVED として記録して残りのステップを続行します。
- 終了時に \`run-summary.md\` が生成されます。

## 自己改善ループ

実行結果をもとに、**ワークフロー自身(各ステップのプロンプト)を AI に改善させる**
ことができます。

\`\`\`bash
node improve.mjs            # 最新の実行を分析して改善案をレポート
node improve.mjs --apply    # prompts/*.md を Codex に直接編集させる
\`\`\`

推奨サイクル: \`run.mjs\` で実行 → \`improve.mjs --apply\` → \`git diff prompts/\` で
差分をレビュー → もう一度実行。このパックを git 管理しておくと、改善をいつでも
巻き戻せます。詳しくは Harness Studio の
docs/SELF_IMPROVEMENT_LOOP_GUIDE.md を参照してください。

## 安全について

- Codex は \`manifest.json\` の \`runner.sandboxMode\`(既定: \`${DEFAULT_SANDBOX_MODE}\`)の
  範囲でのみファイル変更・コマンド実行を行います。
- 対象ディレクトリは git 管理下で実行することを推奨します(差分の確認・巻き戻しのため)。

## カスタマイズ

| ファイル | 内容 |
| --- | --- |
| \`prompts/*.md\` | 各ステップのプロンプト(自由に編集可) |
| \`improve.mjs\` | 自己改善ループ(実行結果からプロンプトを改善) |
| \`manifest.json\` | 実行計画(ステップ順・ループ・サンドボックス・モデル) |
| \`AGENTS.md\` | 対象リポジトリにコピーすると Codex が自動で読むガイダンス |
| \`workflow.json\` | ワークフロー設計の原本(Harness Studio に再インポート可) |

## ステップ一覧

${steps
  .map(
    (planned, index) =>
      `${index + 1}. ${planned.step.name}(${stepKindPresets[planned.step.kind].label})— \`prompts/${planned.slug}.md\``,
  )
  .join("\n")}

Generated by Harness Studio.
`,
});

const runnerPackageJson = (workflow: Workflow): ExportFile => ({
  path: "package.json",
  content: `${JSON.stringify(
    {
      name: `${fileSlug(workflow.name, "workflow")}-codex-runner`,
      private: true,
      version: "0.1.0",
      type: "module",
      scripts: {
        start: "node run.mjs",
      },
      dependencies: {
        "@openai/codex-sdk": "^0.139.0",
      },
    },
    null,
    2,
  )}\n`,
});

export function buildCodexRunnerPack(workflow: Workflow): ExportBundle {
  const plan = planWorkflow(workflow);
  const manifest = buildManifest(workflow, plan);

  const files: ExportFile[] = [
    runnerReadme(workflow, plan.steps),
    runnerPackageJson(workflow),
    { path: "run.mjs", content: RUN_MJS },
    { path: "improve.mjs", content: IMPROVE_MJS },
    { path: "manifest.json", content: `${JSON.stringify(manifest, null, 2)}\n` },
    agentsMd(workflow),
    ...plan.steps.map((planned) => promptFile(workflow, planned)),
    {
      path: "workflow.json",
      content: `${JSON.stringify(buildWorkflowJson(workflow), null, 2)}\n`,
    },
  ];

  return {
    name: `${fileSlug(workflow.name, "workflow")}-codex-runner`,
    description:
      "OpenAI Codex SDK でワークフローを自動実行するランナー(対象リポジトリのファイル編集・コマンド実行が可能)",
    files,
  };
}
